app_id: "d5c6b98c-c440-46dd-8e64-8fda39beeda8"
app_secret: "LJFUgXFv4de1b38fdCfLTSY?]=H/r@X8"
redirect: "http://localhost:8000/tutorial/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"